### ISSUE TITLE
點讚後沒有刷新頁面可以無限制點擊

### ISSUE THREAD

**Issue by Hsins** [persilee/adonis_pro#1]
![image](https://user-images.githubusercontent.com/26391143/50286335-04972600-049a-11e9-8a7e-e0812e0a30b6.png)

如圖所示，也會使得觀看點讚的文章會出現多篇

**Comment by persilee** [comment]
感谢关注，这个我测试过好几次，都只能点击一次，也不会出现多篇，我这里是正常的。
在代码里也有控制点赞后就会取消点击事件
```js
if (likeElement.hasClass('active')) likeElement.unbind('click')
```

**Comment by Hsins** [comment]
> 感谢关注，这个我测试过好几次，都只能点击一次，也不会出现多篇，我这里是正常的。
> 在代码里也有控制点赞后就会取消点击事件

現在我這邊測試也是正常的了，不過點讚後取消點擊事件，這樣就不能把讚收回來了呢…

**Comment by persilee** [comment]
> > 感谢关注，这个我测试过好几次，都只能点击一次，也不会出现多篇，我这里是正常的。
> > 在代码里也有控制点赞后就会取消点击事件
> 
> 现在我这边测试也是正常的了，不过点赞后取消点击事件，这样就不能把赞收回来了呢？

是的，这个地方还可以改善。因为匿名也可以点赞，而无法记录匿名到数据库，所以只能取消点击事件，否则可以和 `Follow` 功能一样，点击 like 再次点击 取消 like ... ,

**Comment by Hsins** [comment]
我覺得 Adonis.js 框架整體的架構性很棒，而且這個專案目前應該算是使用 Adonis 搭建的一個較為完整的專案（至少我在 GitHub 上找不到其他的，就連官方本身提供的都有版本較舊的問題，幾個月沒更新了），看到後立刻拿您的代碼來學習了。

目前覺得有一些可以再改善的地方，像是：

- username 應該多做一個 validation 避免掉空格和特殊字符（ex: /, ', \, @, #, $, %, &, *, ., !, ~)
- Editor 可以不用佔到全屏幕，上方還是可以留原來的 navbar，不然會找不到取消貼文的地方…

**Comment by persilee** [comment]
> 我覺得 Adonis.js 框架整體的架構性很棒，而且這個專案目前應該算是使用 Adonis 搭建的一個較為完整的專案（至少我在 GitHub 上找不到其他的，就連官方本身提供的都有版本較舊的問題，幾個月沒更新了），看到後立刻拿您的代碼來學習了。
> 
> 目前覺得有一些可以再改善的地方，像是：
> 
> * username 應該多做一個 validation 避免掉空格和特殊字符（ex: /, ', , @, #, $, %, &, *, ., !, ~)
> * Editor 可以不用佔到全屏幕，上方還是可以留原來的 navbar，不然會找不到取消貼文的地方…

感谢你提的建议！
- username 已新增一个 validator 
- Editor 可以点击浏览器的返回或者点击头像会出现工具菜单跳到想去的页面
